// SPDX-License-Identifier: GPL-3.0-or-later
#include "docgen.hpp"

#include "schema.hpp"

#include <format>

namespace undershell {

namespace {
std::string defaultOf(const PropSpec& p) {
  switch (p.kind) {
    case PropSpec::Bool: return p.def != 0 ? "`true`" : "`false`";
    case PropSpec::Number: return p.integer ? std::format("`{}`", static_cast<long>(p.def)) : std::format("`{}`", p.def);
    default: return "`\"" + p.defText + "\"`";
  }
}

std::string valuesOf(const PropSpec& p) {
  switch (p.kind) {
    case PropSpec::Bool: return "`true` / `false`";
    case PropSpec::Number:
      return p.integer ? std::format("{} – {}", static_cast<long>(p.min), static_cast<long>(p.max))
                       : std::format("{} – {}", p.min, p.max);
    case PropSpec::Color: return "palette role (`primary`, `secondary`, `tertiary`, `on_surface`, …) or `#rrggbb`";
    case PropSpec::Enum: {
      std::string s;
      for (const auto& o : p.options) s += (s.empty() ? "" : ", ") + ("`" + o + "`");
      return s;
    }
    default: break;
  }
  return {};
}

void table(std::string& md, const std::string& type) {
  md += "| Key | Values | Default | |\n|---|---|---|---|\n";
  for (const auto& p : schemaFor(type))
    md += std::format("| `{}` | {} | {} | {} |\n", p.key, valuesOf(p), defaultOf(p), p.labelEn);
}
}  // namespace

std::string optionsMarkdown() {
  std::string md;
  md += "# Configuration options\n\n";
  md += "<!-- generated by `undershell --doc` from src/schema.hpp; tests/test_docs.cpp checks it -->\n\n";
  md += "`~/.config/undershell/config.toml` is applied live when saved. Everything here can\n";
  md += "also be changed from the editor's inspector (`undershell msg edit`).\n\n";
  md += "## `[general]`\n\n";
  md += "| Key | Values | Default | |\n|---|---|---|---|\n";
  md += "| `grid` | px | `16` | editor snap step |\n";
  md += "| `noise_reduction` | 0 – 1 | `0.45` | analyser smoothing (Ryoku's cava used 45) |\n";
  md += "| `monstercat` | `true` / `false` | `false` | spread peaks to neighbours |\n\n";
  md += "## Every `[[widget]]`\n\n";
  md += "| Key | Values | Default | |\n|---|---|---|---|\n";
  md += "| `id` | text | type name | unique name (used by `msg set/select/remove`) |\n";
  md += "| `type` | `visualizer`, `clock`, `now_playing` | `\"visualizer\"` | |\n";
  md += "| `output` | connector (`HDMI-A-1`, `eDP-1`, …) | first output | monitor |\n";
  md += "| `x`, `y` | logical px | `0` | position on the output (may hang off an edge) |\n";
  md += "| `width`, `height` | logical px | `800` × `240` | box; the design is fitted into it |\n";
  md += "| `enabled` | `true` / `false` | `true` | |\n";
  md += "| `depth` | `true` / `false` | `true` | pass behind the `wallpaper_depth` foreground |\n\n";
  md += "## `type = \"visualizer\"`\n\nRyoku's desktop spectrum.\n\n";
  table(md, "visualizer");
  md += "\n## `type = \"clock\"`\n\nRyoku's clock faces and date strips.\n\n";
  table(md, "clock");
  md += "\n## `type = \"now_playing\"`\n\nRyoku's now-playing card.\n\n";
  table(md, "now_playing");
  md += "| `music_app` | shell command | `\"spotify\"` | opened by the corner button (not in the inspector) |\n";
  return md;
}

}  // namespace undershell
